# Generated by Django 5.0.4 on 2025-06-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="color",
            field=models.CharField(default="#3788d8", max_length=7),
        ),
    ]
