# Generated by Django 5.0.7 on 2025-05-16 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("school_name", models.CharField(blank=True, max_length=100)),
                ("graduation_year", models.CharField(blank=True, max_length=4)),
                ("certifications", models.TextField(blank=True)),
                ("job_type", models.CharField(blank=True, max_length=30)),
                ("industry", models.CharField(blank=True, max_length=30)),
                ("workstyle", models.CharField(blank=True, max_length=30)),
                ("self_pr", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザ",
                    ),
                ),
            ],
        ),
    ]
