# Generated by Django 5.0.7 on 2025-05-17 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
    ]
