# Generated by Django 5.0.4 on 2025-05-22 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="会社名")),
                ("ceo", models.CharField(max_length=200, verbose_name="取締役代表")),
                ("address", models.CharField(max_length=300, verbose_name="本社所在地")),
                (
                    "established_year",
                    models.CharField(max_length=100, verbose_name="設立年度"),
                ),
                ("capital", models.CharField(max_length=100, verbose_name="資本金")),
                (
                    "employees_count",
                    models.CharField(max_length=100, verbose_name="従業員数"),
                ),
                (
                    "business_content",
                    models.TextField(max_length=600, verbose_name="事業内容"),
                ),
                ("official_website", models.URLField(verbose_name="公式HP")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100, verbose_name="項目名")),
                ("field_value", models.CharField(max_length=255, verbose_name="値")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="information.company",
                    ),
                ),
            ],
        ),
    ]
